# Generated by Django 2.0.2 on 2018-04-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('niveau', models.CharField(max_length=40)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdb.Person')),
            ],
        ),
    ]
