# Generated by Django 2.0.2 on 2018-04-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdb', '0003_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=100),
        ),
    ]
