# Generated by Django 2.0.2 on 2018-04-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdb', '0004_auto_20180402_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.CharField(max_length=40),
        ),
    ]
